### ISSUE TITLE
Phase out use of `pipenv`

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/redmine_docs#26]
We've largely discontinued use of `pipenv` in other SecureDrop repos in favor of a `venv/virtualenv` / `pip-compile` / `requirements.in/requirements.txt`  workflow. For consistency with other docs repos, let's use the same workflow here.

**Comment by eloquence** [comment]
This was done a while ago 03de5533a46fd8da50cd31c5b534fd4477ca6544 but looks like `DEVELOP.md` still needs updating, leaving open until that's done.

**Comment by legoktm** [comment]
DEVELOP was removed in https://github.com/freedomofpress/redmine_docs/pull/48 when we switched to poetry.
