### ISSUE TITLE
Archive repo

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/redmine_docs#62]
Once content is available on docs.securdrop.org
- archive this repo
- work with infra to decommision redmine-specific docs site.

**Comment by legoktm** [comment]
We should add a note to the README pointing people in the right direction before we archive the repo too.

**Comment by nathandyer** [comment]
Great idea @legoktm! PR opened here: #63

**Comment by eloquence** [comment]
@nathandyer Looks like that's merged, should I go ahead and archive at this point?

**Comment by nathandyer** [comment]
@eloquence If it's safe to do so from an infrastructure perspective, yes, we can go ahead and archive. I was tentatively holding off until https://github.com/freedomofpress/infrastructure/issues/4253 was fully completed (with the redirects in place I'm not sure if the old site is still up or not, so if it's already gone then both issues can probably be closed and the archival can be done).

**Comment by eloquence** [comment]
We can unarchive if there are any surprises, but I expect archiving itself should not cause any issues. Doing so no.
